main logics
ldv2018/java-filmorate pull request #1
Opened 2022-11-23 18:19 UTC by ldv2018

2022-11-23 21:03 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-23 21:03 UTC, FanaticFiz commented on note.txt
> +добавление фильма -> /films [post]
Используй markdown `md` тогда уже вместо `txt`

2022-11-23 21:03 UTC, FanaticFiz commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ну что же, начнем с "многоуважаемого" `pom` файла ))

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Ну и как минимум не хватает указания кодировки в `properties<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +package ru.yandex.practicum.filmorate;
Обожаю этот класс, в нём никто не делает ошибок!!! )))

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
В качестве типа нужно использовать интерфейсы! HashMap -> Map

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
static переменные объявляются первыми

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new SaveExeption("film save failed");
Нет, ну как же... до сохранения дело еще не дошло. Тут у нас BadRequestException некорректный запрос!

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
???

Неадекватное кол-во пустых строк это тоже нарушение code style

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film == null || !films.containsKey(film.getId())) {
Зря объединил эти проверки. В одном случае это BadRequest, а в другом: ConflictException

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +package ru.yandex.practicum.filmorate.controller;
К этому классу те же замечания...

2022-11-23 21:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/SaveExeption.java
> +    public SaveExeption() {
Пустой конструктор лишний

2022-11-25 18:29 UTC, ldv2018 commented on note.txt
> +добавление фильма -> /films [post]
Перенес в readme

2022-11-25 18:29 UTC, ldv2018 commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
done

2022-11-25 18:29 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
done

2022-11-25 18:29 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
done

2022-11-25 18:29 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new SaveExeption("film save failed");
done

2022-11-25 18:30 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
done

2022-11-25 18:30 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film == null || !films.containsKey(film.getId())) {
done

2022-11-25 18:30 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +package ru.yandex.practicum.filmorate.controller;
done

2022-11-25 18:30 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/SaveExeption.java
> +    public SaveExeption() {
done

2022-11-26 07:32 UTC, FanaticFiz approved these changes

2022-11-26 07:32 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        FilmValidator.validateFilm(film);
Пока такие валидаторы мы пропускаем... но тебе стоит уже начать применять для валидации спец. библиотеки и заменять ручное написание простых валидаций на аннотации.

2022-11-26 07:32 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ConflictException("Bad id. No user found");
В сообщения всегда полезно добавлять больше известной тебе информации...
Вот например тут ты проверял по конкретному id.
Его и надо было добавить `"Not found user by id: " + id`

2022-11-26 07:32 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmValidator.java
> +            throw new ValidationException("Film name is blank");
ValidationException это тоже частный случай BadRequestException 

Ведь если к нам пришли с не валидными входными данными это и есть ничто иное как плохой запрос...

2022-11-29 20:13 UTC, merged