Add friends likes
ldv2018/java-filmorate pull request #2
Opened 2022-12-03 23:57 UTC by ldv2018

2022-12-04 09:01 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService userService;
mark the field as `final`

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
>  package ru.yandex.practicum.filmorate.exceptions;
Именование этого пакета выбивается... остальные ты именовал в единственном числе!

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/handler/ErrorHandler.java
> +        log.info("400 {}", e.getMessage());
логировать лучше со стектрейсом, передавая 3-й параметр и не на уровне `info` это же ошибка!

`log.info("400 {}", e.getMessage(), e);`

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            throw new ConflictException(HttpStatus.NOT_FOUND, "Bad id " + id + ". No film found");
Если мы что-то не нашли то это не может быть ConflictException, это NotFoundException !

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private int id = 1;
ВСЁ ! Теперь у нас есть хранилище, это его работа присваивать `id`

Надо унести туда...

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    List<Film> getFilms();
Давай в сервисах использовать глагол `get`, а в хранилищах `find`

`getFilms -> findAll` `getById -> findById`

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Film deleteLike(int filmId, int userId);
что тут делают `public` ? Это же интерфейс!

2022-12-04 09:01 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film getFilmById(int id);
Если возвращается одиночная сущность, то удобно использовать `Optional` и метод `orElseThrow`, попробуй!

2022-12-04 17:00 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-04 17:00 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +//        if (!filmStorage.findFilmsId().contains(id)) {
Если ты будешь торопиться и оставлять мусор в коде мы будет проходить итерацию за итерацией.
А ожидание проверки может длится часами, так что не спеши и проверяй код перед отправкой!

Это, кстати, обязательно требование у моих подопечных на работе - проверить код самостоятельно!

2022-12-04 17:00 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        return filmStorage.findFilmById(id);
Ты зря перенёс ексепшн в хранилище.
Теперь сервис ничего не делает. А хранилище занимается тем чем не должно!

2022-12-05 04:22 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        checkId(id);
Ну да тут определённо происходит странное.
Вызываем `checkId` - идём в хранилище за пользователем первый раз.
Вызываем `checkFriends` - идём в хранилище за пользователем второй раз.
`userStorage.findUserById` - третий раз.

Проверки не лишние конечно, но надо один раз достать пользователя!

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        checkId(id);
Теперь по вопросу добавления.
Друзья у тебя как Set и это правильно.
Именно поэтому можно просто добавлять id.

```
	public void addFriend(long userId, long friendId) {
		User user = storage.get(userId);
		User friend = storage.get(friendId);
		user.getFriendIds().add(friendId);
		friend.getFriendIds().add(userId);
	}
```

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        return Optional.ofNullable(userStorage.findUserById(id))
Давай тогда и `Optional` дожимать... он далее будет нужен просто всегда.

Ты должен не тут это оборачивать, а прям из хранилища надо возвращать.
Вот такая сигнатура у интерфейса будет:

```
public interface UserStorage {
    Optional<User> findById(int id);
}
```

Когда на репозитории и хибер будешь переезжать, ты уже будешь готов к тому что там тоже всё через Optional...

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film findFilmById(int id);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `filmService.createFilm()`

Получается масло-масляное! 

Лучше: `filmService.create()` `userService.create()`

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    private void checkId(int id) {
По поводу этих методов проверок.
Проверка подразумевает возвращение результата проверки, а у нас просто кидание ексепшена, поэтому подобный метод лучше назвать честно: `throwПоКакойтоПричине`

Например: `throwIfUserNotValid`

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmService.class);
логгеру нет причины давать модификатор `static`

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        if (film == null) {
На самом деле то что пришел null, т.е. совсем какая-то фигня, надо было проверить на контроллере!
Это его зона ответственности - проанализировать входные параметры и говорить BAD_REQUEST на простые валидации, не требующие анализа бизнес правил.

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        if (!filmStorage.findFilmsId().contains(film.getId())) {
Вот это
```
        if (!filmStorage.findFilmsId().contains(film.getId())) {
            throw new NotFoundException(HttpStatus.NOT_FOUND, "Bad id " + film.getId() + ". No film found");
        }
```

Можно заменить методом в хранилище:

```
boolean isAlreadyExist(long id);
```

2022-12-05 04:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void checkFilmAndUserId(int filmId, int userId) {
Разделить на два метода: 

`throwIfFilmNotValid` `throwIfUserNotValid`

2022-12-05 22:16 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        checkId(id);
Разобрался

2022-12-05 22:25 UTC, ldv2018 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void checkFilmAndUserId(int filmId, int userId) {
Так а теперь когда берем элемент, то .orElseThrow будет бросать исключение, если такой фильм/пользователь пустой по этому id. Больше проверять не надо? И проверка отрицательных id в запросе, это же BAD_REQUEST? Тогда его можно было бы в контроллере проверять - но по тестам это должно быть NOT_FOUND.

2022-12-06 03:36 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private void checkFilmAndUserId(int filmId, int userId) {
Следуй заложенной тестами спецификации. id могут передать каким угодно, хоть отрицательным, мы поищем сущность и скажем NOT_FOUND

Да с введением orElseThrow что то может измениться и тут.

2022-12-06 17:04 UTC, FanaticFiz approved these changes

2022-12-06 17:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        User userId = userStorage.find(id).orElseThrow(() ->
Именно так, только давай каждое действие в цепочке переносить на новую строку.

2022-12-06 17:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +public interface UserStorage {
Хороший интерфейс нет желания, не чувствуешь в себе силы?
К следующему разу вывести из двух интерфейсов универсальный?

2022-12-16 18:37 UTC, merged